apiVersion: v1
kind: Service
metadata:
 name: probabilitysubnpservice-srv
spec:
 type: NodePort
 selector:
  app: probabilitysubservice
 ports:
  - name: probabilitysubservice
    protocol: TCP
    port: 80
    targetPort: 80