apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulatorservice
  template:
    metadata:
      labels:
        app: simulatorservice
    spec:
      containers:
        - name: simulatorservice
          image: samilxvi/simulatorservice:latest
---
apiVersion: v1
kind: Service
metadata:
  name: simulator-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: simulatorservice
  ports:
  - name: simulatorservice
    protocol: TCP
    port: 80
    targetPort: 80
