apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stockservice
  template:
    metadata:
      labels:
        app: stockservice
    spec:
      containers:
        - name: stockservice
          image: samilxvi/stockservice:latest
---
apiVersion: v1
kind: Service
metadata:
  name: stock-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: stockservice
  ports:
  - name: stockservice
    protocol: TCP
    port: 80
    targetPort: 80
  - name: stockgrpc
    protocol: TCP
    port: 666
    targetPort: 666